defaults: &defaults
  docker:
    - image: circleci/node:8.11.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "woo-gim@users.noreply.github.com"
            git config --global user.name "woo-gim"
            echo "machine github.com login woo-gim password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=woo-gim yarn run publish-gh-pages
