# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
  - &filter-only-master
    branches:
      only:
        - master

defaults: &defaults
  docker:
    - image: circleci/node:8.11.1

version: 2
jobs:
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "woo-gim@users.noreply.github.com"
            git config --global user.name "woo-gim"
            echo "machine github.com login woo-gim password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=woo-gim yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
        # filters: *filter-only-master
